命令稿啟動於 2017年03月11日 上午 09:47:35
]0;~
[32mChia@MSI [33m~[0m
$ whoami; pwd
Chia
/home/Chia
]0;~
[32mChia@MSI [33m~[0m
$  git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager
user.email=ire33164@gmail.com
user.name=ire33164
core.editor=vim
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ire33164/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;~
[32mChia@MSI [33m~[0m
$ git clone https://github.com/<your github account>/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.giti/lab1.gitr/lab1.gite/lab1.git3/lab1.git3/lab1.git1/lab1.git6/lab1.git4/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~
[32mChia@MSI [33m~[0m
$ exit

命令稿已於 2017年03月11日 上午 09:49:09
 完成